-- create type called grocery
-- create table called shopping_list

-- The shopping_list table should have the following 6 columns. None of the columns should allow null values.

-- A primary key column id
-- A name column
-- A price column that should not be a string and support 2 decimal places.
-- A date_added column that should default to now().
-- A checked column that should be a BOOLEAN with a default of false.
-- A category column. Use the grocery type you created for this column.
-- Once you've written the create.shopping-list.sql file you should be able to create the type and table using the following command:

-- psql -U dunder_mifflin -d knex-practice -f ./sql-scripts/create.shopping-list.sql

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(12, 2) NOT NULL, -- max total of 12 digits, 2 of which occur after the dot
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOLEAN DEFAULT false NOT NULL,
  category grocery NOT NULL
);